#!/bin/sh

# Verbatim from  http://sources.redhat.com/ml/automake/2002-06/msg00038.html

#
# Copyright (c) 2006, 2007, 2008 Neil Walkinshaw and Kirill Bogdanov
# 
# This file is part of StateChum
# 
# StateChum is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
# 
# StateChum is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# StateChum. If not, see <http://www.gnu.org/licenses/>.
# 

# This Makefile aims to build the jni interface to UMFPACK, using ATLAS.
# The aim is to solve sparse systems of linear equations with millions of 
# variables.
set -x
libtoolize --force --copy
aclocal -I config -I m4
automake --foreign --add-missing --force-missing  --copy
autoconf

