/* Copyright (c) 2011 The University of Sheffield.
 * 
 * This file is part of StateChum
 * 
 * StateChum is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * StateChum is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with StateChum.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

/*
 * ErlangModuleViewer.java
 *
 * Created on Feb 17, 2011, 9:37:59 AM
 */
package statechum.Interface;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.List;

import javax.swing.JLabel;
import javax.swing.WindowConstants;

import statechum.analysis.Erlang.ErlangLabel;
import statechum.analysis.Erlang.ErlangModule;

import com.ericsson.otp.erlang.OtpErlangObject;

/**
 * 
 * @author ramsay
 */
public class ErlangModuleViewer extends javax.swing.JFrame {

	/**
	 * ID for serialisation
	 */
	private static final long serialVersionUID = -4531477809121868480L;

	/** Creates new form ErlangModuleViewer */
	public ErlangModuleViewer() {
		initComponents();
	}

	public ErlangModuleViewer(ErlangModule m) {
		this();
		displayModule(m);
		this.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
	}

	protected ErlangModule module;

	public void displayModule(ErlangModule mod) {
		module = mod;
		moduleName.setText(mod.name);
		this.setTitle(mod.name);
		JLabel ta = new JLabel("<html>");
		for (List<OtpErlangObject> argList : mod.behaviour.getInitArgs()) {
			if (!ta.getText().equals("<html>")) {
				ta.setText(ta.getText() + "<br />");
			}
			StringBuffer argsAsString = new StringBuffer(ta.getText());
			argsAsString.append(' ');
			boolean first = true;
			for (OtpErlangObject o : argList) {
				if (!first)
					argsAsString.append(',');
				else
					first = false;
				argsAsString.append(o);
			}
			ta.setText(argsAsString.toString());
		}
		ta.setText(ta.getText() + "</html>");
		initVals.getViewport().removeAll();
		initVals.getViewport().add(ta, BorderLayout.CENTER);
		behaviour.setText(mod.behaviour.toString());
		ta = new JLabel("<html>");
		for (ErlangLabel a : mod.behaviour.getAlphabet()) {
			if (!ta.getText().equals("<html>")) {
				ta.setText(ta.getText() + "<br />");
			}
			ta.setText(ta.getText() + a.toString());
		}
		ta.setText(ta.getText() + "</html>");
		alphabet.getViewport().removeAll();
		alphabet.getViewport().add(ta, BorderLayout.CENTER);
		ta = new JLabel("<html>");
		for (String a : mod.behaviour.getDependencies()) {
			if (!ta.getText().equals("<html>")) {
				ta.setText(ta.getText() + "<br />");
			}
			ta.setText(ta.getText() + a);
		}
		ta.setText(ta.getText() + "</html>");
		dependencies.getViewport().removeAll();
		dependencies.getViewport().add(ta, BorderLayout.CENTER);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		moduleName = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		behaviour = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		alphabet = new javax.swing.JScrollPane();
		dependencies = new javax.swing.JScrollPane();
		jLabel3 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		initVals = new javax.swing.JScrollPane();
		jButton2 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

		moduleName.setText("jLabel1");

		jLabel1.setText("Behaviour:");

		behaviour.setText("jLabel2");

		jLabel2.setText("Alphabet:");

		jButton1.setText("Close");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		alphabet.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

		dependencies
				.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

		jLabel3.setText("Dependencies:");

		jLabel5.setText("Module:");

		jLabel6.setText("Init values:");

		initVals.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

		jButton2.setText("Use for trace generation");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(12, 12,
																		12)
																.addComponent(
																		jLabel6,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		453,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		jLabel3))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		initVals,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		453,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(18, 18,
																		18)
																.addComponent(
																		dependencies,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		299,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(12, 12,
																		12)
																.addComponent(
																		alphabet,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		786,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(12, 12,
																		12)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel5)
																								.addGap(25,
																										25,
																										25)
																								.addComponent(
																										moduleName,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										javax.swing.GroupLayout.DEFAULT_SIZE,
																										Short.MAX_VALUE))
																				.addComponent(
																						jLabel2,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						786,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel1)
																.addGap(6, 6, 6)
																.addComponent(
																		behaviour,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		371,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(533, Short.MAX_VALUE)
								.addComponent(jButton2)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jButton1).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(12, 12, 12)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel5)
												.addComponent(moduleName))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel1)
												.addComponent(behaviour))
								.addGap(27, 27, 27)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jLabel6)
												.addComponent(jLabel3))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		dependencies,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		164,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(6, 6, 6))
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		initVals,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		164,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
								.addComponent(jLabel2)
								.addGap(6, 6, 6)
								.addComponent(alphabet,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										278,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton1)
												.addComponent(jButton2))));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(
			@SuppressWarnings("unused") java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		this.setVisible(false);
		this.dispose();
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
		ErlangTraceGenerator gen = new ErlangTraceGenerator();
		gen.setAlphabet(module.behaviour.getAlphabet());
		gen.setVisible(true);
		this.setVisible(false);
		this.dispose();
	}// GEN-LAST:event_jButton2ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		ErlangModuleViewer emv = new ErlangModuleViewer();
		if (args.length > 0) {
			try {
				emv.displayModule(ErlangModule.loadModule(args[0]));
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		emv.setVisible(true);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane alphabet;
	private javax.swing.JLabel behaviour;
	private javax.swing.JScrollPane dependencies;
	private javax.swing.JScrollPane initVals;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel moduleName;
	// End of variables declaration//GEN-END:variables
}
