/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Traces.java
 *
 * Created on Apr 14, 2011, 3:01:10 PM
 */
package statechum.Interface;

import java.awt.BorderLayout;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import statechum.apps.QSMTool;

/**
 *
 * @author ramsay
 */
public class Traces extends javax.swing.JFrame {

    protected static ArrayList<String> alphabet;
    protected static String filename;
    protected static int poscount;
    protected static int negcount;

    /** Creates new form Traces */
    public Traces() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        filenameLabel.setText(filename);
        tracecountLabel.setText("" + (poscount + negcount) + " (" + poscount + " pos, " + negcount + " neg)");

        JLabel ta = new JLabel("<html>");
        for (String a : alphabet) {
            if (!ta.getText().equals("<html>")) {
                ta.setText(ta.getText() + "<br />");
            }
            ta.setText(ta.getText() + a);
        }
        ta.setText(ta.getText() + "</html>");
        alphabetPane.getViewport().removeAll();
        alphabetPane.getViewport().add(ta, BorderLayout.CENTER);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        filenameLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tracecountLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        alphabetPane = new javax.swing.JScrollPane();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Trace file name:");

        filenameLabel.setText("filename");

        jLabel2.setText("Traces found:");

        tracecountLabel.setText("traces");

        jLabel3.setText("Alphabet:");

        jButton1.setText("Run QSM in manual mode");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Run QSM with the Erlang Auto-Answer wrapper");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(alphabetPane, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tracecountLabel)
                            .addComponent(filenameLabel)))
                    .addComponent(jLabel3))
                .addContainerGap())
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(389, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filenameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tracecountLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alphabetPane, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        QSMTool.main(new String[]{filename});
    }//GEN-LAST:event_jButton1ActionPerformed

    protected static void addAlphabetElements(String line) {
        String[] elems = line.split(" ");
        for (String e : elems) {
            if (!alphabet.contains(e)) {
                alphabet.add(e);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Load and check the Traces file
        if (args.length < 1) {
            throw new RuntimeException("No traces file supplied!");
        }
        filename = args[0];
        poscount = 0;
        negcount = 0;
        alphabet = new ArrayList<String>();

        try {
            BufferedReader input = new BufferedReader(new FileReader(filename));
            String line;
            while ((line = input.readLine()) != null) {
                line = line.trim();
                if (line.startsWith("+")) {
                    poscount++;
                    addAlphabetElements(line.substring(1));
                } else if (line.startsWith("-")) {
                    negcount++;
                    addAlphabetElements(line.substring(1));
                }
            }
            input.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Traces().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane alphabetPane;
    private javax.swing.JLabel filenameLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel tracecountLabel;
    // End of variables declaration//GEN-END:variables
}
